default:
	/usr/local/bin/javac -classpath .:../lib/cs.jar:../lib/chapman.jar:../lib/mmmysql2.jar:../lib/mail.jar:..lib/activation.jar -g ../metdemo/*.java ../metdemo/Attach/*.java ../metdemo/AlertTools/*.java ../metdemo/CliqueTools/*.java ../metdemo/DataBase/*.java ../metdemo/MachineLearning/*.java ../metdemo/Tables/*.java ../metdemo/Tools/*.java ../metdemo/Window/*.java ../metdemo/Parser/*.java ../metdemo/experiment/

clean:
	rm -f *.class *~ Attach/*.class AlertTools/*.class CliqueTools/*.class DataBase/*.class MachineLearning/*.class Tables/*.class Tools/*.class Window/*.class Parser/*.class experiment/*.class

